name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gallery
        uses: actions/checkout@v3.3.0
        with:
          path: gallery
          fetch-depth: 0
          ref: main
          
      - name: Add upstream remote
        working-directory: gallery
        run: |
          git remote add upstream https://github.com/flutter/gallery
          git fetch upstream
      
      - name: Update main branch
        working-directory: gallery
        run: |
          git checkout main
          git reset --hard upstream/main
      
      - name: Push
        working-directory: gallery
        run: |
          git push
